# Generated by Django 5.1.2 on 2024-11-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_category_menuitem_description_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
