# Generated by Django 5.1.2 on 2024-11-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_table_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
